# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TSBHfq9OF-1WhgR1ARvTef0eIwVXD9T
"""

import pandas as pd
datos=pd.read_csv("/content/drive/MyDrive/Festivales_database_limpia.csv", delimiter=';')
datos