# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMtIhyVUo0BhlF38kF27FTsjGx5V4nzz
"""

import pandas as pd
datos=pd.read_csv("/content/Recintos_database_limpia (3).csv", delimiter=";")
datos