# -*- coding: utf-8 -*-
"""codigo_para_visualizar_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BQZyj5_sG1lEVj4XsIXIksqsrn4CXw7
"""

import pandas as pd
import altair as alt
import numpy as np # para strip plot o jitter

data = pd.read_csv('/content/recintos_actualización_tabla_dinámica.csv', delimiter=';')
data

data['Capacidad máxima'] = pd.to_numeric(data['Capacidad máxima'].replace("S/I", pd.NA), errors='coerce')

df = data.dropna(subset=["Capacidad máxima"])

# Gráfico de burbujas por propósito
chart = alt.Chart(df).mark_circle(size=150).encode(
    x=alt.X("Capacidad máxima:Q", title="Capacidad máxima del recinto"),
    y=alt.Y("PROPOSITO:N", title="Propósito del recinto"),
    color=alt.Color ("PROPOSITO:N", scale=alt.Scale(range=['#FFABC5','#FF5187','#DF4575','#A34EA0','#3F4270'])),
    tooltip=["Nombres de recintos", "PROPOSITO", "Capacidad máxima"]
).properties(
    title="Recintos por Propósito y su Capacidad Máxima",
    width=700,
    height=300
).configure_axis(
    grid=True
)
# mostrar gráfico de burbujas
chart

chart.save('vis_01.html')