# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Da_3dZ-yqD6JYk2DpLE0-8TVtqAZvmqx
"""

import pandas as pd
datos=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Conciertos_database_limpia.csv", delimiter=';')
datos