# -*- coding: utf-8 -*-
"""codigo_para_visualizar_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XGn9uacnSZwr_bKxcpMlAYVquyCqnjQ
"""

import altair as alt
import pandas as pd

datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Artistas por recinto_2.0.csv')

chart_csv= alt.Chart(datos).mark_bar(

    cornerRadiusTopLeft=3,
    cornerRadiusTopRight=3

).encode(

    x='Recintos:O',
    y='Cantidad de artistas (2024):Q',

    color=alt.Color('Tipo de artista:N',
     scale=alt.Scale(
                    domain=['Internacional', 'Latinoamericano', 'Latinoamericano y nacional','Nacional'],
                    range=['#FF5187','#A34EA0','#F4F0CD','#3F4270']

       )
    )
).configure_view(step=16, strokeWidth=0).configure_axis(domain=False, labelFontSize=10, titleFontSize=11).properties(width=300, title="Distribución de artistas por recinto (festivales)", background="white").configure_title(anchor='middle', align='center')


chart_csv.show()

chart_csv.save('grafico-recintos-artistas.html')